<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_portal/Desboard.Master" AutoEventWireup="true" CodeBehind="Course.aspx.cs" Inherits="University_Management_System.Admin_portal.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
                            <table class="auto-style6" style="border: medium solid #666666; background-color: #C0C0C0; ">
                        <tr>
                            <td class="auto-style7" colspan="3" style="text-align: center">Add User</td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                <asp:Label ID="lb_user" runat="server" Enabled="False" Text="User Name"></asp:Label>
                            </td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_user_name" runat="server"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rvf_user" runat="server" ControlToValidate="tb_user_name" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp; </td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                <asp:Label ID="lb_pass" runat="server" Enabled="False" Text="Password"></asp:Label>
                            </td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_pass" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rfv_pass" runat="server" ControlToValidate="tb_pass" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp;&nbsp;
                                </td>
                        </tr>
                        <tr>
                            <td class="auto-style17" style="text-align: right">
                                <asp:Label ID="lb_pass0" runat="server" Enabled="False" Text="ReType Password"></asp:Label>
                            </td>
                            <td class="auto-style15">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_re_pass" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td class="auto-style1">
                                <asp:RequiredFieldValidator ID="rfv_pass0" runat="server" ControlToValidate="tb_re_pass" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
                                <br />
                                <asp:CompareValidator ID="CompareValidator1" runat="server" ControlToCompare="tb_pass" ControlToValidate="tb_re_pass" Display="Dynamic" ErrorMessage="Password Not match" ForeColor="Red" SetFocusOnError="True" ValidationGroup="val_user"></asp:CompareValidator>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" class="auto-style5" style="text-align: center">
                                <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_up_Click"/>
                            </td>
                        </tr>
                    </table>
          <br>
    <br />
<br />
                    <asp:GridView ID="dgv_user" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_user_SelectedIndexChanged" OnRowDeleting="dgv_user_RowDeleting">
                        <AlternatingRowStyle BackColor="White" />
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
<br />
<br />
<br />
</asp:Content>
